-- 관계가 있는 테이블의 레코드만 JOIN = INNER JOIN

-- ANSI SQL
SELECT * FROM MEMBER INNER JOIN NOTICE ON MEMBER.ID=NOTICE.WRITER_ID;

-- ORACLE SQL
SELECT * FROM MEMBER, NOTICE WHERE MEMBER.ID=NOTICE.WRITER_ID;

-- INNER JOIN의 RECORD 수
-- : OUTER(관계가 없는 레코드들)를 제거한 자식 테이블의 레코드 수
-- → INNER JOIN: 부모는 참조하고 있는 레이블 수만큼 복제가 되어 합쳐짐
