MEMBER LEFT/RIGHR/FULL OUTER JOIN NOTICE ON MEMBER.ID = NOTICE.WRITER_ID;

-- INNER JOIN
SELECT * FROM NOTICE N JOIN MEMBER M ON N.WRITER_ID=M.ID;


-- OUTER JOIN
-- LEFT OUTER LABLE도 조인
-- ANSI SQL
SELECT * FROM NOTICE N LEFT OUTER JOIN MEMBER M ON N.WRITER_ID=M.ID;
SELECT * FROM NOTICE N LEFT JOIN MEMBER M ON N.WRITER_ID=M.ID;
-- ORACLE SQL
SELECT * FROM NOTICE N, MEMBER M WHERE N.WRITER_ID=M.ID(+);

-- RIGHT OUTER LABLE도 조인
-- ANSI SQL
SELECT * FROM NOTICE N RIGHT OUTER JOIN MEMBER M ON N.WRITER_ID=M.ID;
SELECT * FROM NOTICE N RIGHT JOIN MEMBER M ON N.WRITER_ID=M.ID;
-- ORACLE SQL
SELECT * FROM NOTICE N, MEMBER M WHERE N.WRITER_ID(+)=M.ID;


-- LEFT AND RIGHT OUTER LABLE도 조인
-- ANSI SQL
SELECT * FROM NOTICE N FULL OUTER JOIN MEMBER M ON N.WRITER_ID=M.ID;
SELECT * FROM NOTICE N FULL JOIN MEMBER M ON N.WRITER_ID=M.ID;
-- ORACLE SQL
-- FULL OUTER JOIN 표현식 X
