-- SELECT, FROM, WHERE, GROUP BY, HAVING, ORDER BY


-- 이름 기준 역순정렬 조회
SELECT * FROM MEMBER ORDER BY NAME DESC;
SELECT * FROM NOTICE ORDER BY HIT DESC;

-- 회원 중에서 박씨 성을 가진 회원 조회, 단 나이 오름차순 정렬
SELECT * FROM MEMBER WHERE NAME LIKE '박%' ORDER BY AGE ASC;

-- 2차 정렬
SELECT * FROM NOTICE ORDER BY HIT DESC, REGDATE DESC;
