SELECT ROWNUM, ID, TITLE, WRITER_ID, REGDATE, HIT
FROM NOTICE
WHERE
GROUP BY
ORDER BY HIT;

-- ROWNUM은 WHERE절 이후 만들어지므로 이후 ORDER BY 진행 시, ROWNUM이 섞이게 됨
-- 정렬 후 ROWNUM를 부여하고 싶을 때는 ROW_NUMBER() 사용

SELECT ROW_NUMBER() OVER (ORDER BY HIT), ID, TITLE, WRITER_ID, REGDATA, HIT
FROM NOTICE;

-- ROWNUM처럼 특정 일련번호가 아니라 등수를 부여하고 싶을 때는 RANK 활용
SELECT RANK() OVER (ORDER BY HIT), ID, TITLE, WRITER_ID, REGDATE, HIT
FROM NOTICE;

-- 공동 4등이 있을 경우, 그 다음 등수는 RANK(): 6등, DENSE_RANK(): 5등
SELECT DENSE_RANK() OVER(ORDER BY HIT), ID, TITLE, WRITER_ID, REGDATE, HIT
FROM NOTICE;

-- 그룹별로 등수를 부여하고 싶을 때는 PARTITION BY 사용
SELECT DENSE_RANK() OVER (PARTITION BY WRITER_ID ORDER BY HIT DESC), ID, TITLE, WRITER_ID, REGDATE, HIT
FROM NOTICE;
