-- 회원별 게시글 수를 조회
-- 단, 게시글이 2 미만인 레코드만 출력

SELECT WRITER_ID, COUNT(N.ID)
FROM NOTICE N
WHERE COUNT(N.ID)<2
GROUP BY WRITER_ID;

-- 작성 순서: SELECT FROM WHERE GROUP BY HAVING ORDER BY
-- 실행 순서: FROM WHERE GROUP BY HAVING ORDER BY SELECT
-- 집계함수는 GROUP BY 이후에 사용할 수 있는데, 실행 순서 상 WHERE가 GROUP BY 앞에 위치해 있으므로 사용 불가
-- WHERE 대신 HAVING 사용

SELECT WRITER_ID, COUNT(N.ID)
FROM NOTICE N
GROUP BY WRITER_ID
HAVING COUNT(N.ID)<2;
