SELECT N.ID, N.TITLE, N.WRITER_ID, M.NAME WRITER_NAME, COUNT(C.ID) CNT
FROM MEMBERS M
RIGHR OUTER JOIN NOTICES N ON M.ID=N.WRITER
LEFT OUTER JOIN COMMENTS C ON N.SEQ=C.NOTICESEQ
GROUP BY N.SEQ, N.TITLE, N.WRITER, M.NAME;

CREATE VIEW NOTICEVIEW
AS
SELECT N.ID, N.TITLE, N.WRITER_ID, M.NAME WRITER_NAME, COUNT(C.ID) CNT
FROM MEMBERS M
RIGHR OUTER JOIN NOTICES N ON M.ID=N.WRITER
LEFT OUTER JOIN COMMENTS C ON N.SEQ=C.NOTICESEQ
GROUP BY N.SEQ, N.TITLE, N.WRITER, M.NAME;

-- VIEW를 이용한 QUERY
SELECT * FROM NOTICEVIEW WHERE TITLE LIKE '%오%'
ORDER BY SEQ DESC;
