-- 현재 시간을 얻는 함수
SELECT SYSDATE FROM DUAL; -- ORACLE SERVER 시각
SELECT CURRENT_DATE FROM DUAL; -- 사용자 개별 시각
SELECT SYSTIMESTAMP FROM DUAL; -- SYSDATE에 MILLISECOND 추가
SELECT CURRENT_TIMESTAMP FROM DUAL;

-- 세션 시간과 포맷 변경
ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS';
-- NLS: NATIONAL LANHUAGE SUPPORT;
ALTER SESSION SET TIME_ZONE='-08:00';
ALTER SESSION SET TIME_ZONE='09:00'; -- 한국 TIMEZONE


-- 날짜 추출 함수
SELECT EXTRACT(YEAR  FROM SYSDATE) FROM DUAL;
SELECT EXTRACT(MONTH FROM SYSDATE) FROM DUAL;
SELECT EXTRACT(DAY FROM SYSDATE) FROM DUAL;
-- SELECT EXTRACT(MINUTE FROM SYSDATE) FROM DUAL;
-- invalid extract field for extract source
SELECT EXTRACT(MINUTE FROM SYSTIMESTAMP) FROM DUAL;
-- SELECT EXTRACT(SECOND FROM SYSDATE) FROM DUAL;
-- invalid extract field for extract source
SELECT EXTRACT(SECOND FROM SYSTIMESTAMP) FROM DUAL;


-- 가입 회원 중 비수기(2, 3, 11, 12)월에 가입한 회원 조회
SELECT * FROM MEMBERS WHERE EXTRACT(MONTH FROM REGDATE) IN (2, 3, 11, 12);


-- ADD_MONTHS(날짜, 정수): 날짜를 누적하는 함수
SELECT ADD_MONTHS(SYSDATE, 1) FROM DUAL;
SELECT ADD_MONTHS(SYSDATE, -1) FROM DUAL;

-- 가입 회원 중 가입한지 6개월이 안되는 회원 조회
SELECT * FROM MEMBERS WHERE SYSDATE < ADD_MONTHS(REGDATE, 6);
SELECT * FROM MEMBERS WHERE ADD_MONTHS(SYSDATE, -6) < REGDATE;


-- MONTHS_BETWEEN(날짜, 날짜)
SELECT MONTHS_BETWEEN(SYSDATE, TO_DATE('2013-12-25')) FROM DUAL;

-- 가입 회원 중 가입한지 6개월이 안되는 회원 조회
SELECT * FROM MEMBERS WHERE MONTHS_BETWEEN(SYSDATE, REGDATE) < 6;
-- 차이가 실수로 반환, 비교 연산자 사용


-- NEXT_DAY(입력 날짜, 다음 요일): 입력 날짜 기준 다음 요일의 일자 반환하는 함수
SELECT NEXT_DAY(SYSDATE, '토요일') FROM DUAL;
SELECT NEXT_DAY(SYSDATE, '토') FROM DUAL;
SELECT NEXT_DAY(SYSDATE, 7) FROM DUAL;


-- LAST_DAY(날짜): 입력 월의 마지막 일자 반환
SELECT LAST_DAY(SYSDATE) FROM DUAL;


-- ROUND/TRUNC(날짜, 포맷): 지정된 범위에서 날짜를 반올림하는/자르는 함수
SELECT ROUND(SYSDATE, 'CC'), TRUNC(SYSDATE, 'CC') FROM DUAL;
-- CC: 세기, 01/01/01 01/01/01
SELECT ROUND(SYSDATE, 'YEAR'), TRUNC(SYSDATE, 'YEAR') FROM DUAL;
-- YEAR: 연도, 23/01/01 23/01/01
SELECT ROUND(SYSDATE, 'Q'), TRUNC(SYSDATE, 'Q') FROM DUAL;
-- Q: 분기, 23/04/01 23/01/01
SELECT ROUND(SYSDATE, 'MONTH'), TRUNC(SYSDATE, 'MONTH') FROM DUAL;
-- MONTH: 달, 23/03/01 23/02/01
SELECT ROUND(SYSDATE, 'W'), TRUNC(SYSDATE, 'W') FROM DUAL;
-- W: 해당 월의 첫날의 주의 기준으로 잡음
-- 23년 2월 1일: 수요일, 수요일을 기준으로 반올림, 버림
SELECT ROUND(SYSDATE, 'DAY'), TRUNC(SYSDATE, 'DAY') FROM DUAL;
-- DAY: 입력된 날짜의 일요일 날짜 반환
SELECT ROUND(SYSDATE, 'D'), TRUNC(SYSDATE, 'D') FROM DUAL;
-- D: 입력된 날짜의 일요일 날짜 반환
SELECT ROUND(SYSDATE, 'HH'), TRUNC(SYSDATE, 'HH') FROM DUAL;
-- HH: 시간, 2023-02-26 14:00:00 2023-02-26 14:00:00
SELECT ROUND(SYSDATE, 'MI'), TRUNC(SYSDATE, 'MI') FROM DUAL;
-- MI: 분, 2023-02-26 14:21:00 2023-02-26 14:20:00

-- 날짜 입력 시 '2001-02-03' 기재 시, STRING 처리가 될 수 있으므로 TO_DATE('2001-02-03') 이용
-- SYSDATE FORM 변경, ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS';
