CREATE TABLE MEMBER
(
    ID       VARCHAR2(50),
    PWD      NVARCHAR2(50),
    NAME     NVARCHAR2(50),
    GENDER   NCHAR(2), --NCHAR(2): 4byte, CHAR(2 CHAR): 6byte
    AGE      NUMBER(3),
    BIRTHDAY CHAR(10),
    PHONE    CHAR(13),
    REGDATE  DATE
    
);

DROP TABLE MEMBER;

ALTER TABLE MEMBER MODIFY ID NVARCHAR2(50);
ALTER TABLE MEMBER DROP COLUMN AGE;
ALTER TABLE MEMBER ADD EMAIL VARCHAR2(200);

--MEMBER TABLE에서 직접 편집이 가능하므로 DDL의 ALTER을 사용하는 일은 적음
