-- DOMAIN: NOT NULL
CREATE TABLE TEST(
	ID VARCHAR2(50) NOT NULL,
	EMAIL VARCHAR2(200) NULL,
	PHONE CHAR(13) NOT NULL
)

INSERT INTO TEST(ID) VALUES('222');
-- SQL ERROR: ORA-01400: NULL을 TABLE_COL에 삽입할 수 없습니다

-- NOT NULL 제약조건 추가
ALTER TABLE TEST MODIFY EMAIL VARCHAR2(200) NOT NULL;
-- 또는 테이블 편집 - 널이 아님 체크


CREATE TABLE TEST(
	ID VARCHAR2(50) NOT NULL,
	EMAIL VARCHAR2(200) NULL,
	PHONE CHAR(13) NOT NULL,
	PWD VARCHAR2(200) DEFAULT '111'
)


-- DOMAIN: DEFAULT
-- DEFAULT 제약조건 추가
ALTER TABLE TEST MODIFY EMAIL VARCHAR2(200) DEFALUT '111';
-- 또는 테이블 편집 - 기본값 설정(함수 형식-SYSDATE, SYSTIMESTAMP 가능)
